### ISSUE TITLE
bit-reproducibility from restarts  

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/DATM-MOM6-CICE5#1]
If you write an intermediate restart and then start from that restart, the answer is not the same at the end of the run.

**Comment by JessicaMeixner-NOAA** [comment]
The reproducibility regression test can be updated now after updating to the latest MOM6 (https://github.com/NOAA-EMC/MOM6/pull/22) which sets up functionality for easily outputting intermediate restarts for MOM6.

**Comment by DeniseWorthen** [comment]
I'm going to close this issue. If fixing the restart repro in the coupled model (issue [#227](https://github.com/ufs-community/ufs-weather-model/issues/227)) does not produce datm-mom6-cice6 restart repro (it should) then we can re-create the issue in the unified repo.
