### ISSUE TITLE
gefs forcing time does not match cfsr

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/DATM-MOM6-CICE5#12]
The GEFS forcing files appear to be off-set in time from the CFSR. At hour 18, the CFSR appears to have the correct SWrad location over the central US; the GEFS SWrad is not correct for hour 18.

![cfsr_DSWRF_2011100218](https://user-images.githubusercontent.com/40498404/80487206-6e470000-892a-11ea-883a-9719e4df0283.jpg)
![gefs_DSWRF_2011100218](https://user-images.githubusercontent.com/40498404/80487208-6edf9680-892a-11ea-9429-95951b081758.jpg)

**Comment by hyunchul386** [comment]
I would like to update the mismatch between GEFS/CFSR.
Following is clarifying from Gary, PNL

...
 The data in that file is a 6-h forecast from 12Z, (so valid at 18z).

Output from nemsio_get indicates this, but apparently the nfhour variable isn't in the netcdf file.    Here's what I see for 2018123100:

[Gary.Bates@hfe12 2018123100]$ /home/Gary.Bates/HERA/postproc/ncep_post/util/exec/nemsio_get bfg_2018123100_fhr00_control idate
 idate=        2018          12          30          12           0           0
           1
 idate_ymdh=2018123012
[Gary.Bates@hfe12 2018123100]$ /home/Gary.Bates/HERA/postproc/ncep_post/util/exec/nemsio_get bfg_2018123100_fhr00_control nfhour
 nfhour=           6

Hope this helps,
Gary
...

I will fix the time stamp in GEFS data and update it.

Hyun-Chul

**Comment by junwang-noaa** [comment]
Hyun Chul,

The fields in the file do not look like a 6hr forecast from 12Z.

**Comment by hyunchul386** [comment]
Jun

Any reasons why the fields in the file do not look like the 6h forecast
from 12Z,
and what do you think about the fields?

Thanks,
Hyun-Chul

**Comment by junwang-noaa** [comment]
If it's 6hr forecast from 12Z, the sun's location (shortwave) won't be in
the area of Africa/Europe, but in America.

**Comment by hyunchul386** [comment]
Hmm, that's right.

I guess, GEFS is a 6 hour forecast from 00Z, so for example,
in the case of 2000-01-01 00Z, GEFS would be 2000-01-01 06Z.

Hyun-Chul

**Comment by hyunchul386** [comment]
Indeed, it seems that GEFS would be correct the 6 hour forecast from 12Z.
In the case of 2000-01-01 00Z, GEFS would be 1999-12-31 18Z.

Attached is a comparison of DSRF of CFSR (black: 2000-01-01 00Z,
red: 2000-01-01 06Z) and GEFS(green: 2000-01-01 00Z, blue: 2000-01-01 06Z)

Here, it is shown that the time off-set is not exactly 6 hour between
GEFS/CFSR
(black and blue).
But, still I am considering fixing the GEFS time stamp from green to blue.

Hyun-Chul

**Comment by junwang-noaa** [comment]
The figure from GEFS looks like fh00 at 12Z  or,  6hr forecast from 06Z,
not 6hr forecast from 00Z

**Comment by hyunchul386** [comment]
Well, If there is 12 hour off-set between CFSR and GEFS,
then the phase would be around 180 degree,
and the figure shows the phase difference is about 90 degree.
