### ISSUE TITLE
Convert NEMSCompsetRun to rt.sh in DATM-MOM6-CICE5

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/DATM-MOM6-CICE5#20]
A simple regression test system (rt.sh) will be set up to run DATM-MOM6-CICE5 regression tests, which are currently run using NEMSCompsetRun. All 4 tests will be converted to rt.sh on Hera and Orion.

**Comment by flampouris** [comment]
Thank you, Bin!
