### ISSUE TITLE
The ocean component cannot receive flux fields computed in CMEPS mediator

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/DATM-MOM6-CICE5#48]
## Description
When CMEPS mediator is used in DATM-MOM6-CICE5, the MOM6 component cannot receive flux fields computed in CMEPS.

## To Reproduce the behavior
1. Checkout cmpes_test branch from github.com/binli2337/DATM-MOM6-CICE5.
2. Make the 1-hr cold-start run using "rt_cmeps.conf1".

**Comment by binli2337** [comment]
To reproduce the failed run:
1. Checking out cmeps_test branch from github.com/binli2337/DATM-MOM6-CICE5.
2. cd DATM-MOM6-CICE5/tests
3. ./rt.sh -k -l rt_cmeps.conf1

**Comment by DeniseWorthen** [comment]
Please try setting the weights back to the original bulk-formula methods and retesting using the changes show [here](https://github.com/NOAA-EMC/CMEPS/compare/emc/develop...DeniseWorthen:bugfix/datm).

I put the bulk fluxes in w/o testing. I think I just have the weight values incorrect and it needs to be debugged.

**Comment by DeniseWorthen** [comment]
I believe this issue is resolved by CMEPS PR [#13](https://github.com/NOAA-EMC/CMEPS/pull/13) and through the inclusion of the aoflux_run phase in the run sequence.
